# Generated by Django 5.1 on 2024-08-28 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asmhomeoapp', '0001_initial'),
    ]

    operations = [
    ]
